### ISSUE TITLE
UnderFlow error when not using numba

### ISSUE THREAD

**Issue by volpx** [marl0ny/QM-Simulator-1D#1]
On my machine (python 3.7, numpy 1.16, sympy 1.4, linux amd64) numpy rises an underflow error (and exits without opening the tk window) when numba is not installed/used. The line is the np.matmul in QM_1D_TI:302. Everything is left by default and installing/using numba don't raise the problem.

**Comment by marl0ny** [comment]
Does replacing that particular line with `np.dot(np.linalg.inv(A), B)` remove the error?
You may also have to replace line 320 of QM_1D_TI.py with  `wavefunction.x = np.dot(self.U, wavefunction.x)`. I've made those changes in the attached file:
[QM_1D_TI.zip](https://github.com/marl0ny/1D-Quantum-Mechanics-Applet/files/3439395/QM_1D_TI.zip)

**Comment by volpx** [comment]
Changing only line 302 does solve the problem, I also thought that matmul was an alias for dot but apparently it isn't. The numpy reference says:
"matmul differs from dot in two important ways.
• Multiplication by scalars is not allowed.
• Stacks of matrices are broadcast together as if the matrices were elements."
Which does not explain this behavior.
